### ISSUE TITLE
기존 저장소는 어떻게 하나요?

### ISSUE THREAD

**Issue by anemochore** [hangulize/hangulize#2]
기존 저장소에는 리부트 공지나 새 저장소 주소가 없어 혼동이 생길 수 있을 듯합니다.

또한 기존 저장소의 이슈 중 해결되지 않은 것도 남아 있고요(기능 이슈가 아니라 변환 규칙에 관한 이슈).
혹시 다른 저장소의 이슈를 그대로 가져오는 게 가능할까요?
https://github.com/sublee/hangulize/issues

사소한 문제지만 시간이 되실 때 해결해주시면 좋겠습니다.

**Comment by sublee** [comment]
좋은 지적이네요. 기존 저장소의 설명문구와 README에 이전 안내를 추가하고, 변환 규칙 이슈를 추려서 이쪽으로 옮겨오겠습니다.

**Comment by sublee** [comment]
모두 정리했습니다.
