### ISSUE TITLE
러시아어 알렉산드르

### ISSUE THREAD

**Issue by chongdae** [hangulize/hangulize#4]
"Алекса́ндр"가 "알렉사́느드르"로 옮겨지네요. (사와 느 사이에 특수문자 하나 있어요.)

한글라이즈의 출력 결과에 한글이 아닌 글자가 나오지 않도록 필터링할 필요도 있어보입니다.

**Comment by iceager** [comment]
감사합니다. 사전 같은 곳에서 러시아어의 강세 표기에 쓰이는 Combining Acute Accent (U+0301)를 변환 과정에서
걸러내야 하겠네요.

**Comment by sublee** [comment]
제보해주셔서 감사합니다. v0.3.2에서 카테고리가 "Mark"인 글자를 제외하도록 패치했습니다. https://hangulize.org/?lang=rus&word=Алекса́ндр

**Comment by chongdae** [comment]
Алекса́ндр 가 "알렉사느드르"로 옮겨지네요. "Александр"는 "알렉산드르"로 잘 되고 있고요. 마크 제거를 변환 전에 해야할 듯 싶네요.

https://hangulize.org/?lang=rus&word=Александр

**Comment by sublee** [comment]
러시아어 전사 규칙 중에 마크를 구별하는 내용이 있습니다:

https://github.com/hangulize/hangulize/blob/d5da8a4dfa552890454644557cd757edaffd46c4/hgls/rus.hgl#L148-L149

변환 전에 모든 마커를 제거하면 다른 전사 규칙이 영향을 받게 됩니다.

`산` 대신 `사느`가 적힌 건 마크가 단어의 경계처럼 인식됐기 때문일 텐데요, `Алекса́ндр`, `Александр` 모두 `알렉산드르`로 옮길 수 있도록 다른 방법을 강구해보겠습니다.

**Comment by sublee** [comment]
v0.3.3에서 마크를 제거하는 로직을 번복하고, 마크가 키릴문자의 일부로 취급될 수 있도록 패치했습니다. `Алекса́ндр`, `Александр` 모두 `알렉산드르`로 옮길 수 있게 되었습니다.
