### ISSUE TITLE
"한글라이즈 재제작기" 502 Bad Gateway

### ISSUE THREAD

**Issue by kiding** [hangulize/hangulize#8]
https://github.com/hangulize/hangulize/blob/e6721c50d3492dc734d82df7c297c0cf8c26591f/README.md#L123

링크로 연결된 문서를 열람할 수 없습니다. 아마 실제 이슈는 [subl.ee-links](https://github.com/sublee/subl.ee-links) 에서 해결을 해야 할 것 같은데, 일단 기록을 위해 남겨두겠습니다.

**Comment by sublee** [comment]
제보해주셔서 감사합니다! 지금은 해결되었습니다.
